//*******************************************************************
//              
//  FILE:       STDWIN.H
//              
//  AUTHOR:     Keith R. Bergerstock
//              
//  PROJECT:    RX05_START_CELL
//              
//  COMPONENT:  -
//              
//  DATE:       02.04.2004
//              
//  COMMENTS:   - stdandard windows header file
//              
//              
//*******************************************************************

// Includes

#ifndef __WINDOWS_H
    #ifndef STRICT
        #define STRICT
    #endif

    #define WIN32_LEAN_AND_MEAN
    
    #include <windows.h>
    #include <mmsystem.h>
#endif