// STANDARD MENU AND ABOUT BOX ID'S

// icon id's
#define IDI_ICON1		 101

// about box id's
#define IDM_ABOUT		3000
#define IDB_BITMAP		3005
#define IDD_ABOUT_OK	3010
#define IDD_DISPLAY 	3030
#define IDD_CANCEL		3020


// menu id's
// common menu items
#define  IDM_NEW		1010
#define  IDM_OPEN		1020
#define  IDM_SAVE		1030
#define  IDM_SAVE_AS	1040
#define  IDM_PRINT		1050
#define  IDM_PAGE_SETUP 1060
#define  IDM_PRNT_SETUP 1070
#define  IDM_EXIT		1080

#define  IDM_INDEX		9010
#define  IDM_KEYBOARD	9020
#define  IDM_COMMANDS	9030
#define  IDM_PROCEDURES 9040
#define  IDM_USING_HELP 9050

