CFLAGS =
BASE = C:\myrograms\vs2019\VC\tools\msvc\14.29.30037\
INC = $(BASE)include
CC = $(BASE)bin\x64\bin\cl.exe

TARGET = hw.exe

objs = hw.obj

srcs = hw.cpp

$(objs):$(srcs)
	echo #(BASE)
	echo #(INC)
	echo #(cCC)
	$(CC) -c $(srcs) -I$(INC)




